### PR TITLE
Display custom emoji's nicely in IRC

### PR DESCRIPTION
**Pull request by macdja38**

### CODE REVIEW

**Comment by ekmartin** [comment]
Would you mind adding a test for this? Something similar to https://github.com/reactiflux/discord-irc/blob/master/test/bot.test.js#L207-L226

**Comment by macdja38** [comment]
@ekmartin does that test work?

**Comment by ekmartin** [comment]
Brilliant, thanks!

**Comment by ekmartin** [comment]
Published in version [2.0.2](https://github.com/reactiflux/discord-irc/blob/master/CHANGELOG.md#202---2016-10-02) :)

**Comment by macdja38** [comment]
Awesome, thank you!

**Pull request merged**
