### PR TITLE
Closes #299

### LINKED ISSUE #299: Multicharacter command characters
I put
```json
"commandCharacters": ["@@", "$"]
```
in my config, and it works fine for the prefix $ but not the prefix @@, as it's more than one character. I know it's a rare case but I'm using 2 characters as the input character for my bot, shouldn't be too hard to fix.

### PR DESCRIPTION
**Pull request by xbony2**
(With help from @ekmartin :P I cannot JavaScript)

### CODE REVIEW

**Comment by ekmartin** [comment]
Thanks! Do you want to try to add a test for it too? It should probably look something like this: https://github.com/xbony2/discord-irc/blob/5c927a5e1080d73e5fa7de075b436010bc704573/test/bot.test.js#L461-L481

```js

  it('should support multi-character command prefixes', function () {
    const bot = new Bot({ ...config, commandCharacters: ['@@'] });
    const text = '@@test command';
    const message = {
      content: text,
      mentions: { users: [] },
      channel: {
        name: 'discord'
      },
      author: {
        username: 'test',
        id: 'not bot id'
      },
      guild: this.guild
    };

    this.bot.sendToIRC(message);
    ClientStub.prototype.say.getCall(0).args.should.deep.equal([
      '#irc', 'Command sent from Discord by test:'
    ]);
    ClientStub.prototype.say.getCall(1).args.should.deep.equal(['#irc', text]);
  });
```

**Comment by ekmartin** [comment]
After modifying `bot.test.js` you can run the tests with `npm test`.

**Comment by Throne3d** [comment]
@xbony2 It looks like you need to remove the trailing spaces on line 810 ([here](https://github.com/reactiflux/discord-irc/pull/301/files#diff-c714594bba933f47822fe05838444913R810)) and also use `bot` not `this.bot` where the test has `this.bot.sendToIRC(message);` on line 827 ([here](https://github.com/reactiflux/discord-irc/pull/301/files#diff-c714594bba933f47822fe05838444913R827)) for the linter to pass. If you can, you might want to run `npm test` locally before pushing it to check that it works after that? (The continuous integration tool shows this [here](https://travis-ci.org/reactiflux/discord-irc/jobs/276611338#L1140).)

Thanks!

**Comment by xbony2** [comment]
@Throne3d yeah, npm pointed it out to me. Thanks. `npm test` gives a happy-looking result so unless anyone has any complaints this should be good to go ^_^

**Pull request merged**
