### PR TITLE
Rename ircPreventMention to parallelPingFix

### PR DESCRIPTION
**Pull request by Throne3d**
Per #517, the config name isn't very clear. Since we haven't yet cut a release with it, we rename it here.

Probably not the best name but I don't want to waste too much time thinking of a perfect one.

### CODE REVIEW

**Comment by MikkelDK** [comment]
What about @everyone? Is it possible to prevent that? @Throne3d

**Comment by Throne3d** [comment]
On the discord side of things? You can remove the bot's ability to "Mention Everyone" using Discord's usual permissions panel.

**Comment by MikkelDK** [comment]
Oh, cool! thanks <3

**Comment by MikkelDK** [comment]
@Throne3d is it possible for the IRC can't use everyone tag?

<Bot1337> <@Mikkel> @everyone (ignore this on discord

And I will could see the tagging on discord:

**Comment by Throne3d** [comment]
On Discord, you need to remove the `Mention Everyone` permission from the bot.

**Comment by MikkelDK** [comment]
@Throne3d It can still tag everyone... No matter what.

It's removed on role + on the bot =) so it can still tag everyone. ;/

**Comment by Throne3d** [comment]
@MikkelDK I have it successfully set up in my own server without the ability to ping everyone, so you must have something misconfigured in your Discord settings. Try to set a permission on the channel, for the bot, that explicitly denies "Mention Everyone". I can't help further than this – if you're still having trouble, you'll need to get someone to help you set Discord's permissions up correctly.

**Comment by MikkelDK** [comment]
@Throne3d 

"parallelPingFix": true < does it need to be true or false? 🤔

**Comment by Throne3d** [comment]
`parallelPingFix` has nothing to do with the bot's ability to ping `@everyone` or `@here`.

**Pull request merged**
