### PR TITLE
Add `ircPreventMention` option

### PR DESCRIPTION
**Pull request by qaisjp**
I have the same username on both Discord and IRC. If I write a message in Discord, I receive a nickalert (a "notification", or a "mention") in IRC, which can be very annoying. This PR adds an option (defaults to "on") to prevent that from happening.

By inserting any zero width character (in this pull request, I use a zero width space) somewhere in the printed username you can prevent a nickalert from occurring, with the name looking exactly the same.

For example, with username `john`, I slice `j`, add a zero-width-space, and add `ohn` to the end. This looks like `john`, but is actually `j?ohn` where `?` is the zero width character. 

For usernames that are one character long, the zero width character is at the end of the username (the code does not crash). Depending on IRC client settings, this may or may not notify the client.

The final commit is required so that `ircNickColor` does not overwrite the `displayUsername` change earlier on by `ircPreventMention`. Colours will remain the same as the code that generates the colour still uses `nickname`.

I've actually tested functionality, and only authored it in the GitHub interface because it's easier than using Vim on my server!

### CODE REVIEW

**Comment by qaisjp** [comment]
This breaks a bunch of tests... I'll write new tests.

**Comment by qaisjp** [comment]
Should I fix the broken tests by setting the ircPreventMention setting to false in the test config, and then writing one test that checks the on/off option?

**Comment by ekmartin** [comment]
#193 implemented this, but was reverted because of #196. Even though this puts it behind a config option, I don't think it's a good idea to add something that potentially causes issues for IRC clients nonetheless.

Maybe your IRC client supports disabling mentions for a specific channel?

**Comment by qaisjp** [comment]
Ah, that's a shame. I did not notice this had already been implemented.

Also, it seems like one of the issues in #196 (macOS, Chrome, IRCCloud) no longer occur. See below:

image


I use `\u200B` whereas the previous PR used `\u200d`. If I get confirmation on iOS that things are OK, will there be any possibility of this PR being reopened?

I know XChat hates symbols, so I'll do a check there and if XChat doesn't complain, it's unlikely it causes issues on other desktop clients.

**Comment by Throne3d** [comment]
This PR looks like it basically implements [this suggestion](https://github.com/reactiflux/discord-irc/issues/197#issuecomment-286859889) from issue #197, which I think is a reasonable compromise.

I don't know what systems had trouble with the notifications, though – perhaps we should consider that this character could interact differently, and so push it and revert if there are further bug reports?

**Comment by ekmartin** [comment]
I'm not completely sure - it's still sort of a hack. What are some use cases where either disabling highlights for that IRC channel or just leaving the channel altogether isn't enough?

**Comment by qaisjp** [comment]
@ekmartin When you want to use both clients. My Discord server doesn't have all the channels on the IRC server I frequent, so I need to use both IRC and Discord. Having to flip between both clients isn't fun, but replying to whichever I have open at the time is more convenient.

I've been using this edit since the creation of this PR (in a 52 person IRC channel), and today I've just added this bot (with this mod) to another server (in a 76 person IRC channel).

No complaints so far. I'll come back later and give feedback from the bigger server.

**Comment by qaisjp** [comment]
No issues have been reported from the 2nd Discord guild. I'm running it on a third guild now, lets see what they say...

**Comment by qaisjp** [comment]
It's running on three guilds — no issues have been reported.

**Comment by webvictim** [comment]
Would love to see this merged!

**Comment by Throne3d** [comment]
My comment would be – it might be easier to have it merged if it defaults to false? Less objectionable. I don't see a major reason *not* to merge it (I would personally find it useful, and would offer to look after this part of code if necessary).

@ekmartin do you have further input here? I think the major blocker was not seeing an obvious use for it, but I do know some people who prefer (for whatever reason) to be in both Discord and IRC. (Perhaps they like the textual logging IRC can provide, and haven't sorted something out for Discord?) It seems slightly out of scope, but not dramatically, as this sort of thing was merged before, then found to cause problems.

**Comment by qaisjp** [comment]
Obviously I'll have to write some tests here for ircPreventMention, but shouldn't these tests pass if ircPreventMention defaults to false?

**Comment by melt7777** [comment]
What a great feature! How can I use this? Is it an option in the config file? Do you have an ASCII-code (Alt-code) for the blank space? Thanks!

**Comment by qaisjp** [comment]
@melt7777 Yes, just add `"ircPreventMention": true` to the config.

The code is `\u200B`

**Comment by Throne3d** [comment]
@qaisjp You're currently inverting the condition – `options.ircPreventMention !== true` is the same as `!(options.ircPreventMention === true)` is the same as `!options.ircPreventMention`.

You probably want just `this.ircPreventMention = options.ircPreventMention`? (That way it defaults to undefined, and must be explicitly set to `true` to attain a truthy value.)

**Comment by melt7777** [comment]
I pulled the latest from git and then added that to my config, pm2 restart discord-irc, and then it joins, but behavior is the same. Also, when I try Change Nickname on the server and change it from melt to m\u200Belt it just makes it that and does not parse the \u control. Does it have to be my username?

**Comment by webvictim** [comment]
@melt7777 I think you're misunderstanding what the feature does. When set to true, the bot will insert a #\u200B# into every <nick> it sends to IRC to try and avoid highlighting the person. You don't need to change your nick on either IRC or Discord at all.

**Comment by anirbanmu** [comment]
Is there any plan to merge this?

**Comment by Throne3d** [comment]
I'm furthering this in #502 (added a test and also fixed the README), plan is to merge it as soon as Travis passes! Gonna close this, accordingly.

Thanks for the contribution. :)

**Pull request closed without merging**
