### PR TITLE
IRC Users joining/parting/quiting 

### PR DESCRIPTION
**Pull request by Ratismal**
I love Discord-IRC, but one of my major gripes with it is that IRC join/part/quit events aren't outputted to discord. I've just been manually changing my local files, but it's a bit irritating to do whenever I update. It would be great if this functionality came installed!

I have implemented this functionality in this branch. Feel free to change it as needed.

As a sidenote, I love the refactor that this code has received! It looks much cleaner.

### CODE REVIEW

**Comment by StrikerMan780** [comment]
Definitely this. Would be nice.

**Comment by polyzium** [comment]
Will this gonna be implemented or not???

**Comment by StrikerMan780** [comment]
Wondering the same.

**Comment by polyzium** [comment]
We need a review on that to make merging possible, i cannot do it because i ain't coder at all. **at least i tried to merge by myself but i failed** so i am waiting for someone to merge it

**Comment by polyzium** [comment]
let's see if that will work))) 52 upvote and 0 downvotes definantly deserve the request to be merged... still i dont much know how github works

**Comment by ask-compu** [comment]
have the devs given up on this project?

**Comment by RoyCurtis** [comment]
Merged this PR into [our fork](https://github.com/Gamealition/GDiscord-IRC), thank you very much @Ratismal !

To get this PR working, [I had to make a few changes to the code](https://github.com/Gamealition/GDiscord-IRC/commit/cf18aa1bdcaa00a1e3da97da566e82e99146bc46).

**Comment by polyzium** [comment]
@RoyCurtis Thanks i hope you will ressurect this project!

**Comment by RoyCurtis** [comment]
I don't think this project needs resurrecting, since the last commit was only 8 days ago. I also don't intend on taking over or providing support; that is purely just for our needs :)

**Comment by Ratismal** [comment]
Glad you got it working @RoyCurtis.

Considering how the last commit was to merge a 14 day old PR, and this PR was from over a year ago to implement basic events, I think there's little hope in the developers merging it.

I'd recommend any developers to manually integrate IRC support into their projects. If you're not a developer, you'll just have to make do.

**Comment by Throne3d** [comment]
Hm, is there a particular reason this PR hasn't been merged? (Maybe because it seems to lack tests?)

**Comment by Throne3d** [comment]
Well, I rebased this anyway (and updated bits of it to use the format of the new code), then added tests and extracted the bit that finds the discord channel, and overall hopefully it'll be readily mergeable.

**Comment by ekmartin** [comment]
Sorry that I haven't replied to this! The reason I didn't merge it originally was the lack of tests and the on by default behavior (needs to be behind a configuration option). 

Let's try to get #207 merged. Thank you for your contribution @Ratismal.

**Comment by ekmartin** [comment]
Released in [2.3.0](https://github.com/reactiflux/discord-irc/blob/master/CHANGELOG.md#230---2017-04-03) - enable by setting `ircStatusNotices` to `true` in your config.

**Pull request closed without merging**
