### PR TITLE
add ignoredWords feature (doesn't forward messages containing an igno…

### PR DESCRIPTION
**Pull request by intrand**
…redWord)

example configuration option (top level JSON key):
"bannedWords": ["pleasebanme", "testsomewords", "thingsYouWouldntPutInACommitMessage"]

tested working, built in docker.

feel free to change code style, naming, whatever you like.

### CODE REVIEW

**Comment by intrand** [comment]
We quickly came to the conclusion that ignoring certain words is great, but insufficient. I will add to the merge request one more change: We added ignored prefixes, too. Since now we have more than one type of thing we filter out, we changed the wording to be uniform and a little more plain about what it does.

In the case of prefixes: Instead of making commands go straight through (like commandPrefix), we want to avoid sending (filter) any message that starts with a particular string.

"filterWords": ["listof", "verybad", "wordsthatarebad"]
"filterPrefix": ["!", "?", "."]

Code of an extremely similar style to follow in the next commit/push. I will add it to this merge request if I can.

**Comment by intrand** [comment]
Have you had a chance to take a look at this?

**Comment by Johj** [comment]
I think adding some granularity to a filters feature would be nice. Something like a hard vs soft mode. Hard would not send at all while soft would regex replace the filter word with a preset like "<censored>".

**Comment by intrand** [comment]
if you want to extend it further, go ahead. We need the capability to completely drop messages with banned words and commands, which have different criteria (contains vs starts with). We don't like the idea of putting "<censored>" or similar in there, but we don't care if there's an option for it -- we just won't use it, hence why I don't want to spend time making it work well.

**Comment by Throne3d** [comment]
Before merging this, I'd want some tests added to the PR – however, it seems like people want a bunch of different ways to ignore people from being relayed by the bot, and I'm not sure what the full set is. I'd like to get some more information on that (and maybe some more general ideas about what features to merge) before getting this in, because we'll want to preserve backwards compatibility once we add this. (See <https://github.com/reactiflux/discord-irc/issues/430#issuecomment-519564514>.)

**Comment by MikkelDK** [comment]
Any ETA about this? @Throne3d @intrand ???

I did test it but seems it doesn't work with "ignoreWords" as an example with "listof"

I can still see it posted on discord.

**Comment by Throne3d** [comment]
Hey! I'm afraid this PR is unlikely to be merged in the foreseeable future. I'm only now maintaining discord-irc for bug fixes and vulnerabilities, as I'm no longer an active user of the project.

I appreciate the contribution, and hope it's useful to anyone who comes across it. If you have the time to maintain a fork, that might be a way to help keep this project developing.

**Pull request closed without merging**
