### PR TITLE
Attachment handling (update)

### PR DESCRIPTION
**Pull request by ThomasWeber**
Handles discord attachments by saying the URL in IRC. Resolves issue #14. Updated to hopefully resolve some of the lint issues.

### CODE REVIEW

**Comment by ekmartin** [comment]
The linting errors are syntax errors, you seem to be missing a closing bracket before the `else if`. Have you tried running the code? I.e. `npm run build` then starting it.

By the way, you don't have to create a new pull request to run the linter and tests, see [here](https://github.com/reactiflux/discord-irc#tests) for how to run them locally.

**Comment by ThomasWeber** [comment]
Er, whoops! I must have pasted it wrong. New to github I wasn't set up to do a normal sync so I just used the web file editor (bad idea). It does run great on my machine and npm run build passes. Will fix and resubmit.

**Comment by ThomasWeber** [comment]
okay, lint seems happy now. Just need to resolve the issues with coverage.

**Comment by ekmartin** [comment]
Sorry about the extremely late answer, but I'm going to close this in favor of #33 (as it has tests and supports multiple attachments). 

My response time on this project has been extremely slow lately. I know how annoying it is to not get adequate answers on a proposed pull request, so apologies for that.

**Pull request closed without merging**
