### PR TITLE
ignoreUsers with discord id 

### PR DESCRIPTION
**Pull request by nsavch**
An attempt to implement suggestion from #489

Works for me, tests and style checks pass.

### CODE REVIEW

**Comment by Throne3d** [comment]
This looks really good, thank you! Would you be able to rebase this onto master? Sorry to have taken so long to review it.

**Comment by Throne3d** [comment]
Actually, I'll see if a merge and a squash works! I've had trouble with lots of merges and rebases in the past, and the GitHub interface doesn't seem to let me rebase it and check it can merge directly, so let's see how goes.

**Comment by Throne3d** [comment]
Thank you for the contribution!

**Comment by nsavch** [comment]
Thanks for merging!

**Pull request merged**
