### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by Throne3d**
After I accidentally pushed to this repository instead of my own, the merge PR for #421's Docker support got automatically closed. I'm also not totally sure how to preserve the old commit history, in light of these all now … being … part of the main branch's … commit history. (A simple rebase didn't seem to work.) Oops. Anyway, you should be able to see that PR for more details.

@ekmartin Sorry about the messy commit history. Does this look okay? Would you be happy to add a Docker Hub image for this, and put the credentials into Travis?

### CODE REVIEW

**Comment by gdude2002** [comment]
Don't worry about attribution, I'm just happy to get this in, haha

**Comment by gdude2002** [comment]
Looks like you've got yourself a merge conflict!

**Comment by Throne3d** [comment]
Fixed, and updated it to use Node 12! Plus I made it _actually_ skip the deploy phase on PRs (when it tests that it merges with master), instead of just on branch pushes.

**Comment by Throne3d** [comment]
I've merged this on my fork, for testing, and had it push to <https://hub.docker.com/r/throne3d/discord-irc> – looks to be working! Reminder before merging: this PR requires the `DOCKER_USERNAME` and `DOCKER_PASSWORD` environment variables to be set, per <https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings> (probably on the master branch only, and definitely don't display the password in the build log).

**Comment by Throne3d** [comment]
This now uses the https://hub.docker.com/r/discordirc/discord-irc repository! I did a test build locally, which seemed to work fine, so now it's just to see if this works on master.

**Comment by Throne3d** [comment]
Worked on master!

Travis build here: https://travis-ci.org/reactiflux/discord-irc/builds/625065797?utm_medium=notification&utm_source=github_status

Docker tags: https://hub.docker.com/repository/docker/discordirc/discord-irc/general (specifically https://hub.docker.com/layers/discordirc/discord-irc/11a534700615be2a7496fac247adc556b3e2e0ba/images/sha256-f5920cc37b2e84c7446744c52b1de6ebcba44f11841ca7444becd453888a00be)

**Pull request merged**
