### PR TITLE
Use nickname, not username, in command prelude

### PR DESCRIPTION
**Pull request by williamjacksn**

### CODE REVIEW

**Comment by ekmartin** [comment]
Nice catch! This means we aren't actually using the username variable anymore though, mind removing it? Here: https://github.com/williamjacksn/discord-irc/blob/7b934e53198cd4caad80c7e7cbf0b3af6ce69473/lib/bot.js#L140

**Comment by williamjacksn** [comment]
You got it!

**Comment by ekmartin** [comment]
Brilliant, thanks.

**Comment by ekmartin** [comment]
Released in version [2.1.2](https://github.com/reactiflux/discord-irc/blob/master/CHANGELOG.md#212---2016-11-01)

**Pull request merged**
